replicaCount: 1

image:
  repository: saikumarnerella90/order-service
  tag: latest  

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 5003

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

