apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "endpoints", "services"]
    verbs: ["get", "list", "watch"]

