apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io

