apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-sa
    namespace: monitoring
roleRef:
  kind: Role
  name: grafana-role
  apiGroup: rbac.authorization.k8s.io
