replicaCount: 1

image:
  repository: saikumarnerella90/payment-service
  tag: latest  

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 5002

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

