replicaCount: 1

image:
  repository: saikumarnerella90/frontend-service
  tag: latest  

imagePullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

