replicaCount: 1

image:
  repository: saikumarnerella90/frontend-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

