adminUser: admin
adminPassword: admin

service:
  type: ClusterIP

rbac:
  create: false

persistence:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local

