apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: auth-service
  endpoints:
  - port: http
    interval: 15s
