replicaCount: 1

image:
  repository: saikumarnerella90/auth-service
  tag: latest  

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

