apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5003

