replicaCount: 1

image:
  repository: saikumarnerella90/user-service
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

