replicaCount: 1

image:
  repository: saikumarnerella90/user-service
  tag: latest  

imagePullPolicy: Always

service:
  type: ClusterIP
  port: 5001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

